- hosts: localhost
  become: yes
  tasks:
  - check_mode: yes
    authorized_key:
       user: root
       state: present
       key: |
         ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDi4AgyjD8szXxs7UcDTqTSoQwqvFUaayvSg2BnHuAl3eIl7exuZKuMhDqRWkCuw+8Nk9IvvPb5qOj9WMWz3T5Nw9wMz6BCEKDLsirU9MwZg7PO0VyX0YjoEY+/B5kuqabG0s7KUjDO1Q0BG2YxTGjClIX8dOzlS4CFa+o9T6+OZm78nTYn4OmIIKn6/qSmtSlZvSO8XYJfa+bNltRNElWJ2Jh8RrkWr/sz6CeroIp3WL8GEz7n1lZpNxC6pDx+UJ9kZjf/PdD8pUhmHjNvD/2NqSB/BGtacuowysh4A3p746nv7v33/vpmSCJcq6lenM5wNkWi5Jj46S+bfBujC5tJ vagrant@localhost.localdomain
